--- # Manage a BIG-IP node

- name: Manage a BIG-IP node
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yaml
  vars:
    # FQDN of the BIG-IP
    bigip: "{{ bigip }}"
    # management port
    server_port: "{{ server_port }}"
    # node IP addresses list
    nodes: [1.1.1.1, 2.2.2.2]
    # state most be enabled or disabled (default is disabled)
    state: "disabled"
    # variables required by F5 module
    provider:
          user: "{{ f5_user }}"
          server: "{{ bigip }}"
          server_port: "{{ server_port }}"
          password: "{{ f5_password }}"
          validate_certs: no

  tasks:
    - name: Get nodes
      register: nodes_output
      bigip_device_facts:
        gather_subset: 
          - nodes
        provider: "{{ provider }}"
    
    - debug: echo {{ item }}
      loop: "{{ query('items', '{{ nodes_output.nodes }}') }}"
      when: item.address in nodes

    - name: Enable/Disable a node
      bigip_node:
        state: "{{ state }}"
        partition: Common
        name: "{{ item.name }}"
        provider: "{{ provider }}"
      loop: "{{ query('items', '{{ nodes_output.nodes }}') }}"
      when: item.address in nodes
  